version: '3.8'

services:
  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile    # pointe sur le Dockerfile à la racine
    container_name: postgres_smartorder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  backend-net:
    driver: bridge
