version: '3.8'
name: smartorder-postgres
services:
  postgres-db:
    image: postgres:15
    container_name: postgres_container_smartorder
    environment:
      POSTGRES_DB: smartOrder
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  backend-net:
