spring:
  output:
    ansi:
      enabled: always
  application:
    name: Smart Order API
  datasource:
    url: 'jdbc:postgresql://localhost:5432/smartOrder'
    username: smartorder_user
    password: V82g!dxgZ!tR9#qm
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: 'N2czNzY0ZWI5MjM0NmRkNzE3NzI4MzQ5ZDk1ZmVmMTQ0MDczNGQ0NzU5NDMyZDhl'

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    ynov.smartorder: INFO
  file:
    name: # <--- important : vide pour désactiver les fichiers logs




