spring:
  application:
    name: Smart Order API
  datasource:
    url: 'jdbc:postgresql://localhost:5432/smartOrder'
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: 'N2czNzY0ZWI5MjM0NmRkNzE3NzI4MzQ5ZDk1ZmVmMTQ0MDczNGQ0NzU5NDMyZDhl'

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


